apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 3
  selector:
    app: hello-pod-v1
  template:
    metadata:
      labels:
        app: hello-pod-v1

    spec:
      containers:
      - name: my-pod
        image: teddy1565/docker-demo
        ports:
        - containerPort: 3000
